---
abstract: 'PSGI toolkit and servers'
author:
  - '- Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
  Test::TCP: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Devel::StackTrace: 0
  Devel::StackTrace::AsHTML: 0
  File::ShareDir: 1.00
  Filesys::Notify::Simple: 0
  Filter::Util::Call: 0
  LWP: 5.814
  Path::Class: 0
  Pod::Usage: 0
  Try::Tiny: 0
  URI: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack.git
version: 0.9031
