---
abstract: 'Perl Superglue for Web frameworks and Web Servers (PSGI toolkit)'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
  Test::TCP: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Devel::StackTrace: 0
  Devel::StackTrace::AsHTML: 0.09
  File::ShareDir: 1.00
  Filesys::Notify::Simple: 0
  HTTP::Body: 1.06
  Hash::MultiValue: 0.05
  LWP: 5.814
  Pod::Usage: 0
  Try::Tiny: 0
  URI: 1.36
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack.git
version: 0.9929
