---
abstract: 'Perl Superglue for Web frameworks and Web Servers (PSGI toolkit)'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Milla version v0.9.6, Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Devel::StackTrace: 1.23
  Devel::StackTrace::AsHTML: 0.11
  File::ShareDir: 1.00
  Filesys::Notify::Simple: 0
  HTTP::Body: 1.06
  HTTP::Message: 5.814
  Hash::MultiValue: 0.05
  LWP::UserAgent: 5.814
  Pod::Usage: 1.36
  Stream::Buffered: 0.02
  Test::TCP: 1.02
  Try::Tiny: 0
  URI: 1.59
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/plack/Plack/issues
  homepage: https://github.com/plack/Plack
  repository: https://github.com/plack/Plack.git
version: 1.0021
x_authority: cpan:MIYAGAWA
x_contributors:
  - 'Aaron Trevena <aaron.trevena@gmail.com>'
  - 'Alex J. G. Burzyński <ajgb@cpan.org>'
  - 'Andrew Rodland <andrew@cleverdomain.org>'
  - 'Andy Wardley <abw@wardley.org>'
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Ask Bjørn Hansen <ask@develooper.com>'
  - 'Bernhard Graf <augensalat@gmail.com>'
  - 'Chia-liang Kao <clkao@clkao.org>'
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'Cosimo Streppone <cosimo@cpan.org>'
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
  - 'Daisuke Murase <typester@cpan.org>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'David E. Wheeler <david@justatheory.com>'
  - 'Eduardo Arino de la Rubia <earino@rent.com>'
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Grant McLean <grant@catalyst.net.nz>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
  - 'Henry Baragar <Henry.Baragar@Instantiated.Ca>'
  - 'Hiroshi Sakai <ziguzagu@gmail.com>'
  - 'Jay Hannah <jay.hannah@iinteractive.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Jiro Nishiguchi <jiro@cpan.org>'
  - 'Johannes Plunien <johannes.plunien@xing.com>'
  - 'John Beppu <john.beppu@gmail.com>'
  - 'John Napiorkowski <jjnapiork@cpan.org>'
  - 'Jonathan Swartz <swartz@pobox.com>'
  - 'Justin Davis <jrcd83@gmail.com>'
  - 'Kang-min Liu <gugod@gugod.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Kazuho Oku <kazuhooku@gmail.com>'
  - 'Lee Aylward <lee@laylward.com>'
  - 'Leo Lapworth <leo@cuckoo.org>'
  - 'Mark Fowler <mark@twoshortplanks.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
  - 'Masahiro Chiba <chiba@everqueue.com>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
  - 'Oliver Gorwits <oliver@cpan.org>'
  - 'Oliver Paukstadt <pstadt@sourcentral.org>'
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Panu Ervamaa <panu.ervamaa@frantic.com>'
  - 'Paul Driver <frodwith@gmail.com>'
  - 'Pedro Melo <melo@simplicidade.org>'
  - 'Peter Flanigan <github@roxsoft.co.uk>'
  - 'Peter Makholm <peter@makholm.net>'
  - 'Piotr Roszatycki <piotr.roszatycki@gmail.com>'
  - 'Rafael Kitover <rkitover@cpan.org>'
  - 'Randy Stauner <randy@magnificent-tears.com>'
  - 'Ray Miller <rm7@sanger.ac.uk>'
  - 'Ricky Morse <remorse@partners.org>'
  - 'Rob Hoelz <rob@hoelz.ro>'
  - 'Ryo Miyake <ryo.studiom@gmail.com>'
  - 'Scott S. McCoy <smccoy@saymedia.com>'
  - 'Shawn M Moore <sartak@gmail.com>'
  - 'Stephen Clouse <stephenclouse@gmail.com>'
  - 'Stevan Little <stevan.little@iinteractive.com>'
  - 'Stuart A Johnston <saj_git@thecommune.net>'
  - 'Takeshi OKURA <okura3@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Tom Heady <tom-github.com@punch.net>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
  - 'Wallace Reis <wreis@123people.com>'
  - 'Yann Kerherve <yann@cyberion.net>'
  - 'Yury Zavarin <yury.zavarin@gmail.com>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - 'chansen <chansen@cpan.org>'
  - 'cho45 <cho45@lowreal.net>'
  - 'chromatic <chromatic@wgz.org>'
  - 'fayland <fayland@gmail.com>'
  - 'franck cuny <franck@lumberjaph.net>'
  - 'hiratara <hiratara@cpan.org>'
  - 'kakuno <kakuno@livedoor.jp>'
  - 'leedo <lee@laylward.com>'
  - 'mala <github@ma.la>'
  - 'osfameron <hakim.cassimally@gmail.com>'
  - 'punytan <punytan@gmail.com>'
  - 'vti <viacheslav.t@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'yappo <yappo@shibuya.pl>'
  - 'Ævar Arnfjörð Bjarmason <avarab@gmail.com>'
  - '唐鳳 <audreyt@audreyt.org>'
